version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - path: .env.local
        required: true
  db:
    image: postgres:latest
    ports:
      - "3001:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pwd